In [1]:
import numpy as np

In [2]:
python_list = [3,2,5,8,4,9,7,6,1]

array = np.array(python_list)
print(array)

[3 2 5 8 4 9 7 6 1]


In [3]:
type(array)

numpy.ndarray

In [4]:
# Creating a 2D array from lists

python_list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]

np.array(python_list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.random.random()

0.16611143397451877

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.random.random((2, 4))

array([[0.00202489, 0.6713621 , 0.55372683, 0.99541148],
       [0.62831911, 0.69599941, 0.68158777, 0.35018871]])

In [17]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])